name: Update GitHub Stats

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Generate GitHub Stats
        uses: cicirello/user-statistician@v1.26.3
        with:
          colors: dark
          include-title: false
          featured-repository: finance-analytics-dashboard
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
